---
name: 🐛 Bug Report
description: Report a reproducible bug
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.
        
        Before sending, please:
        - Check [existing issues](https://github.com/remittor/zapret-openwrt/issues)
        - Read [documentation](https://github.com/remittor/zapret-openwrt/wiki/)

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug description
      description: A clear and concise description of what is not working
      placeholder: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the problem. If you're following a manual, please include a link to it.
      placeholder: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected behavior
      description: A clear and concise description of what was to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ System Information
      description: |
        Information about your system (fill in all that used)
      value: |
        - **OpenWrt version**: 
        - **Zapret version**: 
        - **Router model**: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: strategy
    attributes:
      label: ✅ The NFQWS strategy used
      description: All parameters of the NFQWS strategy, or its name
      placeholder: If the problem is caused by the NFQWS strategy

  - type: textarea
    id: config
    attributes:
      label: ⚙️ System Configurations
      description: |
        Relevant parts of the configuration (remove sensitive information!)
      placeholder: |
        For example:
        - Contents of /etc/config/zapret
        - Firewall configuration (Flow offloading, etc.)
        - Additional configurations required for wireless/network/dhcp, etc.
      render: shell
